// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv.proto

package srv

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SrvRequest struct {
	MethodName           string   `protobuf:"bytes,1,opt,name=methodName,proto3" json:"methodName,omitempty"`
	Model                string   `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SrvRequest) Reset()         { *m = SrvRequest{} }
func (m *SrvRequest) String() string { return proto.CompactTextString(m) }
func (*SrvRequest) ProtoMessage()    {}
func (*SrvRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bbe8325d22c1a26, []int{0}
}

func (m *SrvRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SrvRequest.Unmarshal(m, b)
}
func (m *SrvRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SrvRequest.Marshal(b, m, deterministic)
}
func (m *SrvRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SrvRequest.Merge(m, src)
}
func (m *SrvRequest) XXX_Size() int {
	return xxx_messageInfo_SrvRequest.Size(m)
}
func (m *SrvRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SrvRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SrvRequest proto.InternalMessageInfo

func (m *SrvRequest) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *SrvRequest) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *SrvRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type SrvResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SrvResponse) Reset()         { *m = SrvResponse{} }
func (m *SrvResponse) String() string { return proto.CompactTextString(m) }
func (*SrvResponse) ProtoMessage()    {}
func (*SrvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bbe8325d22c1a26, []int{1}
}

func (m *SrvResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SrvResponse.Unmarshal(m, b)
}
func (m *SrvResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SrvResponse.Marshal(b, m, deterministic)
}
func (m *SrvResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SrvResponse.Merge(m, src)
}
func (m *SrvResponse) XXX_Size() int {
	return xxx_messageInfo_SrvResponse.Size(m)
}
func (m *SrvResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SrvResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SrvResponse proto.InternalMessageInfo

func (m *SrvResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type VersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionRequest) Reset()         { *m = VersionRequest{} }
func (m *VersionRequest) String() string { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()    {}
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bbe8325d22c1a26, []int{2}
}

func (m *VersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionRequest.Unmarshal(m, b)
}
func (m *VersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionRequest.Marshal(b, m, deterministic)
}
func (m *VersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRequest.Merge(m, src)
}
func (m *VersionRequest) XXX_Size() int {
	return xxx_messageInfo_VersionRequest.Size(m)
}
func (m *VersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRequest proto.InternalMessageInfo

type VersionResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bbe8325d22c1a26, []int{3}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*SrvRequest)(nil), "SrvRequest")
	proto.RegisterType((*SrvResponse)(nil), "SrvResponse")
	proto.RegisterType((*VersionRequest)(nil), "VersionRequest")
	proto.RegisterType((*VersionResponse)(nil), "VersionResponse")
}

func init() { proto.RegisterFile("srv.proto", fileDescriptor_2bbe8325d22c1a26) }

var fileDescriptor_2bbe8325d22c1a26 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x50, 0x4d, 0x4b, 0x85, 0x40,
	0x14, 0xd5, 0x22, 0xcb, 0x6b, 0xa4, 0x5c, 0x22, 0x06, 0x17, 0x11, 0x03, 0x51, 0x6d, 0x06, 0xaa,
	0x9f, 0x10, 0xd4, 0xae, 0x85, 0x42, 0xab, 0x36, 0xa6, 0x17, 0x14, 0x46, 0xc7, 0x66, 0xc6, 0xf9,
	0xfd, 0xc1, 0x38, 0x95, 0xef, 0x2d, 0xde, 0xf2, 0x9c, 0xcb, 0xf9, 0xba, 0x90, 0x1a, 0xed, 0xc4,
	0xac, 0x95, 0x55, 0xfc, 0x13, 0xa0, 0xd6, 0xae, 0xa2, 0xef, 0x85, 0x8c, 0xc5, 0x6b, 0x80, 0x91,
	0x6c, 0xaf, 0xba, 0xf7, 0x66, 0x24, 0x16, 0xdf, 0xc4, 0xf7, 0x69, 0xb5, 0x61, 0xf0, 0x12, 0x4e,
	0x46, 0xd5, 0x91, 0x64, 0x47, 0xfe, 0xb4, 0x02, 0x64, 0x70, 0xea, 0x48, 0x9b, 0x41, 0x4d, 0xec,
	0xd8, 0xf3, 0xbf, 0x90, 0xdf, 0x42, 0xe6, 0xdd, 0xcd, 0xac, 0x26, 0x43, 0x78, 0x05, 0x89, 0x26,
	0xb3, 0x48, 0x1b, 0xac, 0x03, 0xe2, 0x05, 0x5c, 0x7c, 0xac, 0x8a, 0x50, 0x84, 0x3f, 0x40, 0xfe,
	0xc7, 0x1c, 0x16, 0x3f, 0xf5, 0x7e, 0x41, 0x4d, 0xda, 0x0d, 0x2d, 0xe1, 0x1d, 0x9c, 0xbd, 0x34,
	0x52, 0xbe, 0x2e, 0x53, 0x8b, 0x99, 0xf8, 0x9f, 0x56, 0x9e, 0x8b, 0x4d, 0x13, 0x1e, 0xe1, 0x23,
	0xc0, 0x1b, 0xd9, 0x10, 0x82, 0xb9, 0xd8, 0x2d, 0x50, 0x16, 0x62, 0x2f, 0x9f, 0x47, 0x5f, 0x89,
	0x7f, 0xd9, 0xf3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x4c, 0x5e, 0x26, 0x3f, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SrvServiceClient is the client API for SrvService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SrvServiceClient interface {
	CallFunc(ctx context.Context, in *SrvRequest, opts ...grpc.CallOption) (*SrvResponse, error)
	GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
}

type srvServiceClient struct {
	cc *grpc.ClientConn
}

func NewSrvServiceClient(cc *grpc.ClientConn) SrvServiceClient {
	return &srvServiceClient{cc}
}

func (c *srvServiceClient) CallFunc(ctx context.Context, in *SrvRequest, opts ...grpc.CallOption) (*SrvResponse, error) {
	out := new(SrvResponse)
	err := c.cc.Invoke(ctx, "/SrvService/CallFunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvServiceClient) GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/SrvService/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SrvServiceServer is the server API for SrvService service.
type SrvServiceServer interface {
	CallFunc(context.Context, *SrvRequest) (*SrvResponse, error)
	GetVersion(context.Context, *VersionRequest) (*VersionResponse, error)
}

// UnimplementedSrvServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSrvServiceServer struct {
}

func (*UnimplementedSrvServiceServer) CallFunc(ctx context.Context, req *SrvRequest) (*SrvResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallFunc not implemented")
}
func (*UnimplementedSrvServiceServer) GetVersion(ctx context.Context, req *VersionRequest) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}

func RegisterSrvServiceServer(s *grpc.Server, srv SrvServiceServer) {
	s.RegisterService(&_SrvService_serviceDesc, srv)
}

func _SrvService_CallFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SrvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvServiceServer).CallFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SrvService/CallFunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvServiceServer).CallFunc(ctx, req.(*SrvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SrvService/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvServiceServer).GetVersion(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SrvService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SrvService",
	HandlerType: (*SrvServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallFunc",
			Handler:    _SrvService_CallFunc_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _SrvService_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "srv.proto",
}
